name: Deploy to Heroku

on: push
#  push:
#    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: disc-golf-bag-builder-service
    env:
      REGISTRY: registry.heroku.com
      APP_NAME: disc-golf-bag-builder-service
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
        # Cannot create an ENV variable using another ENV variable, this is the workaround
      - name: Set Image Tag env var
        run: |
          echo "IMAGE_TAG=$REGISTRY/$APP_NAME/web" >> $GITHUB_ENV
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build -Dquarkus.container-image.tag=$IMAGE_TAG
          docker image ls
      - name: Login to Heroku Registry
        uses: docker/login-action@v3
        with:
          registry: $REGISTRY
          username: ${{ secrets.HEROKU_EMAIL }}
          password: ${{ secrets.HEROKU_API_KEY }}
      - name: Push Docker image
        run: |
          docker push $IMAGE_TAG