# Your workflow name.
name: Deploy to heroku.

# Run workflow on every push to master branch.
on: push
#  push:
#    branches: [main]

# Your workflows jobs.
jobs:
  docker:
    runs-on: ubuntu-latest
    environment: disc-golf-bag-builder-service
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
#      -
#        name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: src/main/docker/
          push: false
          tags: registry.heroku.com/disc-golf-bag-builder-service