name: Deploy to Heroku

on: push
#  push:
#    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: disc-golf-bag-builder-service
    env:
      REGISTRY: registry.heroku.com
      APP_NAME: disc-golf-bag-builder-service
      PROCESS_TYPE: web
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew assemble -Dquarkus.container-image.group=$REGISTRY -Dquarkus.container-image.name=$APP_NAME/$PROCESS_TYPE -Dquarkus.container-image.tag=latest
          docker image ls
      - name: Login to Heroku Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.HEROKU_EMAIL }}
          password: ${{ secrets.HEROKU_API_KEY }}
      - name: Push Docker image to Heroku Registry
        run: |
          docker push $REGISTRY/$APP_NAME/$PROCESS_TYPE
      - name: Release image to Heroku
        run: |
          export HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }}
          heroku container:release $PROCESS_TYPE --app $APP_NAME